name: Elixir CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    merge_group:
      types: [checks_requested]

permissions:
  contents: read

jobs:
  build:

    name: Build and test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Elixir v1.14 OTP25
        uses: erlef/setup-beam@v1
        with:
          elixir-version: '1.14.X' # Define the elixir version [required]
          otp-version: '25.X' # Define the OTP version [required]
      - name: Restore dependencies cache
        uses: actions/cache@v3
        with:
          path: deps
          key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
          restore-keys: ${{ runner.os }}-mix-
      - name: Install dependencies
        run: mix deps.get
      - name: Run tests
        run: mix test

      - name: Set up Elixir v1.15 OTP25
        uses: erlef/setup-beam@v1
        with:
          elixir-version: '1.15.X' # Define the elixir version [required]
          otp-version: '25.X' # Define the OTP version [required]

      - name: Install dependencies
        run: mix deps.get
      - name: Run tests
        run: mix test

      - name: Set up Elixir v1.14 OTP26
        uses: erlef/setup-beam@v1
        with:
          elixir-version: "1.14.X" # Define the elixir version [required]
          otp-version: "26.X" # Define the OTP version [required]
      - name: Install dependencies
        run: mix deps.get
      - name: Run tests
        run: mix test

      - name: Set up Elixir v1.15 OTP26
        uses: erlef/setup-beam@v1
        with:
          elixir-version: '1.15.X' # Define the elixir version [required]
          otp-version: '26.X' # Define the OTP version [required]
      - name: Install dependencies
        run: mix deps.get
      - name: Run tests
        run: mix test

      - name: Set up Elixir v1.16 OTP26
        uses: erlef/setup-beam@v1
        with:
          elixir-version: "1.16.X" # Define the elixir version [required]
          otp-version: "26.X" # Define the OTP version [required]
      - name: Install dependencies
        run: mix deps.get
      - name: Run tests
        run: mix test
